### ISSUE TITLE
Handler Conflict

### ISSUE THREAD

**Issue by elifkizilky** [elifkizilky/SpaceDancers#1]
In our code, the flow statistics and flow removal handlers conflict. Conflicts between event handlers can occur if they interfere with each other or if they make conflicting assumptions about the state of the application. In Ryu, event handlers are executed asynchronously, and it's crucial to ensure that they don't interfere with each other's logic.

Here are some tips to resolve or prevent conflicts between event handlers:

- Avoid Global State: Minimize the use of global state in your Ryu application. If multiple event handlers modify shared state, it can lead to conflicts. Instead, use attributes of your RyuApp class or pass necessary information through event objects.
- Ordering of Decorators: The order in which you apply the set_ev_cls decorators can affect the order in which handlers are called. Consider the order of decorators and whether the order influences the logic.

```
@set_ev_cls(EventA, MAIN_DISPATCHER)
@set_ev_cls(EventB, MAIN_DISPATCHER)
def handler_ab(self, ev):
    # ...

@set_ev_cls(EventB, MAIN_DISPATCHER)
@set_ev_cls(EventA, MAIN_DISPATCHER)
def handler_ba(self, ev):
    # ...
```

- Avoid Blocking Operations: Ensure that your event handlers don't perform long-running or blocking operations that can delay the processing of other events. Use asynchronous programming techniques if needed.
- Logging and Debugging: Add logging statements or print statements within your event handlers to understand the flow of execution and identify any unexpected behavior.
- Review Event Dependencies: If events are related or dependent on each other, ensure that the dependencies are handled correctly. For example, if one event handler relies on the results of another, make sure that the order of execution is appropriate. 
- Handle Exceptions Gracefully: Use try-except blocks to catch and handle exceptions within your event handlers. This prevents exceptions in one handler from affecting the execution of others.

```
@set_ev_cls(EventA, MAIN_DISPATCHER)
def handler_a(self, ev):
    try:
        # Your code here
    except Exception as e:
        self.logger.error(f"Error in handler_a: {e}")
```

- Check Ryu Documentation and Release Notes: Be aware of any specific requirements or considerations for the events you are handling. Review the Ryu documentation and release notes for the version you are using.
- Separate Logic into Methods: If a single event handler has grown too complex, consider separating its logic into multiple methods within your RyuApp class.

**Comment by bgmrsln** [comment]
It turns out the issue was related to idle timeout setting of miss entry flow rule
