### ISSUE TITLE
Gettingg Flow table occupancy ratio

### ISSUE THREAD

**Issue by elifkizilky** [elifkizilky/SpaceDancers#11]
Getting the ratio of occupancy of table size from packet-in and removal
learn how to use tools

**Comment by bgmrsln** [comment]
Starting working on the issue

**Comment by bgmrsln** [comment]
We can get flow table size for each table with: OFPTableStatsRequest, then we can divide this number to the table size we set to find the ratio.


![Image](https://github.com/elifkizilky/SpaceDancers/assets/53114791/9f56f832-1156-4ec5-bd7b-5bd9535eda9f)

**Comment by bgmrsln** [comment]
It says in here that size and characteristics of the flow tables are only dependent on the switch, not defined by the specification: https://stackoverflow.com/questions/37614780/openflow-1-5-1-flow-table-maximum-size . So we need to go with what I offered above

**Comment by bgmrsln** [comment]
Here ı set table size to 5, and pingall, so ratio is %100
![Image](https://github.com/elifkizilky/SpaceDancers/assets/53114791/78bb23c9-0a16-4e2c-8d93-8bfdf5361f4a)

![Image](https://github.com/elifkizilky/SpaceDancers/assets/53114791/7ca53909-8303-432a-800f-f8193459386e)
