### ISSUE TITLE
Writing mininet topology in python

### ISSUE THREAD

**Issue by elifkizilky** [elifkizilky/SpaceDancers#15]
The following links can be used for creating topology in python:
* https://github.com/XuyangCaoUCSD/LeoEM/blob/4488b000c80fe540cd162741186dcbc9486bf88e/emulation_stage/emulator.py#L215 -> can be used to simulate satellite
* https://github.com/rubiruchi/Mininet-emulation/blob/54e0ff878481ab66b47614cd5eb2aa6cb942d003/mininet-testbed/mininet-sim.py#L77 
* https://github.com/santhisenan/SDN_DDoS_Simulation/blob/master/tree_topology.py -> a topology using random flows
* https://github.com/parasgulati8/SDN-Simulation-with-OpenFlow/blob/master/topology.py -> a simple topology
* https://github.com/GuTaoZi/SDN_Simulation/blob/main/controller.py -> for handling adding host and links for the controller

**Comment by elifkizilky** [comment]
- [ ] Learn how to write topology
- [ ] Conclude the topolgy

**Comment by bgmrsln** [comment]
randomly generated topology with machine learning sdn: https://github.com/Bhanudeep/Detection-of-DDoS-attacks-on-SDN-network-using-Machine-Learning-

**Comment by bgmrsln** [comment]
https://gist.github.com/John-Lin/961156c1c6dcac545b41

**Comment by bgmrsln** [comment]
Topology can be created simply but we also need to create hosts from dataset, and replay pcap file on the dataset. tcpreplay can be used for this purpose

**Comment by bgmrsln** [comment]
* https://github.com/smythtech/mininet_pcap_replay/blob/master/mininet_pcap_replay.py pcap file included
* https://mininet.org/api/classmininet_1_1node_1_1Node.html -> setting ip addresses for hosts
* https://mailman.stanford.edu/pipermail/mininet-discuss/2013-May/002216.html -> how to change ip address on mininet

**Comment by bgmrsln** [comment]
tcpreplay manpage: https://tcpreplay.appneta.com/wiki/tcpreplay-man.html

![Image](https://github.com/elifkizilky/SpaceDancers/assets/53114791/fecc94a4-0b50-462a-b177-7b512a386d50)

**Comment by bgmrsln** [comment]
we can set duration to 300 seconds for small examples as I dont know how to cut pcap files
