### ISSUE TITLE
Dataset search for network simulation

### ISSUE THREAD

**Issue by elifkizilky** [elifkizilky/SpaceDancers#16]
https://figshare.com/articles/dataset/Flow_entries_of_the_OpenFlow_/12282341/1 -> flow rules dataset

**Comment by elifkizilky** [comment]
We can use the UNIV1 and UNIV2 datasets. Here is a link I found on the Internet:

- https://pages.cs.wisc.edu/~tbenson/IMC10_Data.html

**Comment by bgmrsln** [comment]
I think the link added has UNI1, UNI2 and PRV1 datasets

**Comment by bgmrsln** [comment]
This is how UNIV1 pt1 is interpreted on Wireshark

![Image](https://github.com/elifkizilky/SpaceDancers/assets/53114791/e833c00b-52a4-4ed2-a194-c6ce2b983e5e)

**Comment by bgmrsln** [comment]
I think untill we integrate satellite these datasets aqre fine. Closing the issue
