### ISSUE TITLE
Calculate and test heuristic for PE

### ISSUE THREAD

**Issue by elifkizilky** [elifkizilky/SpaceDancers#33]

**Comment by elifkizilky** [comment]
Heuristics is calculated for each flow and held in a dictionary.
It needs to be tested.

**Comment by elifkizilky** [comment]
last_hit_time may not work, so we need to change its heuristics. 

`((last_hit - packet_in)/(current_time-packet_in))* total_hits`


instead of the first part, we may put last_duration as well. It is open to testing.

**Comment by bgmrsln** [comment]
(1/(current_time-packet_in))* total_hits
